name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - destination: "platform=iOS Simulator,OS=18.0,name=iPhone 16 Pro"
            xcode: "16.4"
            os: "macos-15"
          - destination: "platform=iOS Simulator,OS=17.0,name=iPhone 15 Pro"
            xcode: "15.4"
            os: "macos-14"
          - destination: "platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro"
            xcode: "14.3.1"
            os: "macos-13"
          
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build for iOS Simulator
      run: |
        xcodebuild build \
          -scheme Zooming \
          -destination "${{ matrix.destination }}" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Run tests
      run: |
        xcodebuild test \
          -scheme Zooming \
          -destination "${{ matrix.destination }}" \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

  package-validation:
    name: Package Validation
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Show Swift version
      run: swift --version
    
    - name: Validate Package.swift
      run: swift package dump-package
    
    - name: Check Package Dependencies
      run: swift package show-dependencies
    
    - name: Validate Package Structure
      run: swift package describe --type json